LTO_ENABLE = yes

VIA_ENABLE = no

TAP_DANCE_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
AUTOCORRECT_ENABLE = yes
CAPS_WORD_ENABLE = yes
TRI_LAYER_ENABLE = yes
NKRO_ENABLE = yes
EXTRAKEY_ENABLE = yes
BOOTMAGIC_ENABLE = yes
